[package]
name = "nw"
version = "0.2.0"
edition = "2021"
authors = ["Sasha Koss <koss@nocorp.me>"]
description = "CLI that detects and runs corresponding script runner"
license = "MIT"

[[bin]]
name = "nw"
path = "src/main.rs"

[dependencies]
