[package]
name = "nw"
version = "0.3.0"
edition = "2021"
authors = ["Sasha Koss <koss@nocorp.me>"]
description = "A tiny CLI that finds and runs the right command runner"
license = "MIT"

[[bin]]
name = "nw"
path = "src/main.rs"

[dependencies]
